import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet" />
      </head>
      <body>
        <header className="headerMain">
          <div className="headerLeft">
            <img src="./myronslogo.png" className="myronsLogo"></img>
          </div>

          <nav className="headerNav">
            <a href="">Menus</a>
            <a href="">Weekly Ad</a>
            <a href="">Contact</a>
            <a href="">About Us</a>
          </nav>

          <div className="headerRight">
            <a>Order Now!</a>
            <a>123-123-4567</a>
          </div>
        </header>
      </body>
    </html>
  );
}
